---
aspects_mysql_client_package_name:
  Debian: "mysql-client-5.6"
aspects_mysql_server_packages:
  mysqlserver:
    state: "present"
    Debian: "mysql-server-5.6"
  mysqlclient:
    state: "present"
    Debian: "mysql-client-5.6"

aspects_mysql_server_init: False
# manage the root user
aspects_mysql_server_root_user: root
aspects_mysql_server_root_password: "password"
aspects_mysql_server_root_password_old: "password"
# set to true when changing the root password.
aspects_mysql_server_root_password_change: False

#For cnf settings, use this format:
# hashname:
#   default: "setting=value"
#   Debian: "setting=Debian specific value."
#   RedHat: "setting=RedHat specific value."
aspects_mysql_server_cnf_mysqld:
#  query_cache_size:
#    default: "query_cache_size = 256M"
#  innodb_buffer_pool_size:
#    default: "innodb_buffer_pool_size = 4G"
#  innodb_log_file_size:
#    default: "innodb_log_file_size = 256M"
  innodb_open_files:
    default: "innodb_open_files = 450"
  innodb_read_io_threads:
    default: "innodb_read_io_threads = 8"
  innodb_write_io_threads:
    default: "innodb_write_io_threads = 8"
  table_definition_cache:
    default: "table_definition_cache = 800"
  table_open_cache:
    default: "table_open_cache = 1200"
  join_buffer_size:
    default: "join_buffer_size = 32M"
#  tmp_table_size:
#    default: "tmp_table_size = 512M"
#  max_heap_table_size:
#    default: "max_heap_table_size = 512M"
  innodb_file_per_table:
    default: "innodb_file_per_table"
  table_open_cache:
    default: "table_open_cache=200"
  wait_timeout:
    default: "wait_timeout=3600"
  interactive_timeout:
    default: "interactive_timeout=14400"
  max_connections:
    default: "max_connections=165"

#mysqlcnf_mysqld_safe_extra_lines:
#  - "open_files_limit = 4096"

aspects_mysql_server_users:
  tester:
    name: tester
    password: "password"
    host: "1.1.1.1"
    dbhost: localhost
    priv: "*.*:ALL"

aspects_mysql_server_databases:
  tester:
    name: test
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4